
server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 235689
    druid:
      initialSize: 5
      maxActive: 20
      maxWait: 6000
      minIdle: 1